### ISSUE TITLE
urgent !!!!!!  / Volleyball-Spike github

### ISSUE THREAD

**Issue by aleanor78** [MathewAaron/Volleyball-Spike#1]
@MathewAaron 
hi, .my name is Aleanor.
I saw your project about volleyball spike simulation in Matlab and I recently started studying biomechanics and wanted to ask if it is possible for me to have the data file so I can run the program and see the results
it won't be published anywhere I swear 
I really want to see a running code for this kind of project in Matlab and your project was the only one from which I could learn anything from. thank you for making it public
I would really like to know more about this project
thanks again
i will be waiting for your reply
Aleanor.H

**Comment by MathewAaron** [comment]
Hi @aleanor78 , 

Thanks for your interest in this project - the dataset is not made public and I won't be able to share the dataset with you. I can maybe show you a sample on how the dataset is presented so you would have idea on how to move ahead. But please let me know if there's any issue with the running of the code, I will be sure to address them. Thanks - Aaron

**Comment by aleanor78** [comment]
@MathewAaron 
Hi, I will appreciate it if you would please show me what will be the results after running the code and how the data is presented and what parameters are essential for a good result.
thanks again 
aleanor
